### PR TITLE
Added flash dump of UF-Instant

### PR DESCRIPTION
**Pull request by robkegeenen**
Thought it might come in useful for others experimenting with RTL9601C based sticks to add a flash dump of a Ubiquiti UFiber Instant.

### CODE REVIEW

**Comment by Anime4000** [comment]
Nice!
How you dump each partition?

**Comment by robkegeenen** [comment]
I enabled the SSH server on the stick (`flash set SERVICE_SSH_ENABLE 1` + `reboot`) and then did `ssh ubnt@192.168.1.1 'cat /dev/mtd0' >dev_mtd0` (for each of the partitions).
The same idea might also work over telnet, but I haven't tried that as I trust SSH more. :slightly_smiling_face:

**Comment by Anime4000** [comment]
I see, this method can do reverse? (Write the partition)

**Comment by robkegeenen** [comment]
Yes, you'll first have to do `flash_eraseall /dev/mtd0` and then you can do `ssh ubnt@192.168.1.1 'cat >/dev/mtd0' <dev_mtd0`.
The only caveat is when writing the rootfs, since the stick is running when you write. It shouldn't cause data corruption as squashfs is read-only anyway, but rebooting just after writing is probably a good idea.

**Pull request merged**
